"""Vocabulary categories, tracked separately from themes and grammar pools.

Themes describe a *situation* (a meeting, a trip); categories describe a
*vocabulary domain* (tools, the body, paperwork). Each worksheet gets a couple
of categories on rotation so every domain is covered over time, and each
category is seeded with core words so the basics are always in the word bank.

Seed lemmas are dictionary forms: infinitives, singular nouns without an
article, masculine singular adjectives.
"""

NOUN = "noun"
VERB = "verb"
ADJECTIVE = "adjective"
ADVERB = "adverb"

SPANISH_VOCABULARY_CATEGORIES = {
    "food_cooking": {
        "label": "food, ingredients and cooking",
        NOUN: [
            "cebolla",
            "ajo",
            "sartén",
            "horno",
            "receta",
            "cuchara",
            "sabor",
            "harina",
        ],
        VERB: ["freír", "hervir", "pelar", "mezclar", "probar", "asar"],
        ADJECTIVE: ["crudo", "picante", "soso", "quemado"],
    },
    "body_health": {
        "label": "the body, symptoms and injuries",
        NOUN: [
            "rodilla",
            "hombro",
            "espalda",
            "garganta",
            "fiebre",
            "herida",
            "tobillo",
        ],
        VERB: ["doler", "toser", "estornudar", "sangrar", "torcerse", "curarse"],
        ADJECTIVE: ["mareado", "hinchado", "agotado"],
    },
    "emotions_personality": {
        "label": "emotions and personality traits",
        NOUN: ["vergüenza", "orgullo", "envidia", "culpa", "ilusión", "nostalgia"],
        VERB: [
            "enfadarse",
            "avergonzarse",
            "alegrarse",
            "arrepentirse",
            "echar de menos",
            "atreverse",
        ],
        ADJECTIVE: [
            "celoso",
            "tacaño",
            "terco",
            "ilusionado",
            "despistado",
            "orgulloso",
        ],
    },
    "home_objects": {
        "label": "household objects and chores",
        NOUN: [
            "grifo",
            "bombilla",
            "enchufe",
            "escoba",
            "cajón",
            "almohada",
            "estantería",
            "manta",
        ],
        VERB: ["barrer", "fregar", "colgar", "tender", "ordenar", "recoger"],
        ADJECTIVE: ["desordenado", "limpio", "polvoriento"],
    },
    "clothing": {
        "label": "clothes, fabrics and fit",
        NOUN: [
            "cremallera",
            "botón",
            "manga",
            "bolsillo",
            "calcetín",
            "bufanda",
            "abrigo",
        ],
        VERB: ["probarse", "abrochar", "coser", "planchar", "encoger", "quitarse"],
        ADJECTIVE: ["ajustado", "holgado", "arrugado", "estampado"],
    },
    "weather_landscape": {
        "label": "weather, seasons and landscape",
        NOUN: [
            "tormenta",
            "trueno",
            "niebla",
            "orilla",
            "acantilado",
            "colina",
            "charco",
        ],
        VERB: ["llover", "nevar", "granizar", "soplar", "helar", "florecer"],
        ADJECTIVE: ["húmedo", "nublado", "despejado", "caluroso"],
    },
    "animals": {
        "label": "animals and pets",
        NOUN: [
            "cerdo",
            "oveja",
            "abeja",
            "hormiga",
            "lobo",
            "gallina",
            "mosca",
            "cachorro",
        ],
        VERB: ["ladrar", "morder", "picar", "criar", "alimentar"],
        ADJECTIVE: ["salvaje", "manso", "peludo"],
    },
    "city_places": {
        "label": "the city, buildings and directions",
        NOUN: [
            "acera",
            "semáforo",
            "ayuntamiento",
            "plaza",
            "barrio",
            "esquina",
            "puente",
        ],
        VERB: ["cruzar", "girar", "aparcar", "perderse", "pasear"],
        ADJECTIVE: ["concurrido", "peatonal", "céntrico"],
    },
    "transport_vehicles": {
        "label": "transport, vehicles and driving",
        NOUN: [
            "billete",
            "andén",
            "rueda",
            "volante",
            "maletero",
            "atasco",
            "gasolinera",
        ],
        VERB: ["conducir", "adelantar", "frenar", "arrancar", "despegar", "aterrizar"],
        ADJECTIVE: ["retrasado", "averiado", "directo"],
    },
    "tools_repairs": {
        "label": "tools, DIY and repairs",
        NOUN: [
            "martillo",
            "destornillador",
            "clavo",
            "tornillo",
            "escalera",
            "pegamento",
            "taladro",
        ],
        VERB: ["atornillar", "clavar", "lijar", "pintar", "arreglar", "romperse"],
        ADJECTIVE: ["roto", "suelto", "oxidado"],
    },
    "money_shopping": {
        "label": "money, prices and shopping",
        NOUN: [
            "recibo",
            "descuento",
            "cuota",
            "deuda",
            "presupuesto",
            "monedero",
            "rebajas",
        ],
        VERB: ["ahorrar", "gastar", "cobrar", "prestar", "devolver", "regatear"],
        ADJECTIVE: ["barato", "caro", "gratuito"],
    },
    "bureaucracy": {
        "label": "bureaucracy and paperwork",
        NOUN: [
            "trámite",
            "ventanilla",
            "formulario",
            "cita previa",
            "sello",
            "fotocopia",
            "certificado",
        ],
        VERB: ["rellenar", "firmar", "tramitar", "renovar", "solicitar", "caducar"],
        ADJECTIVE: ["caducado", "obligatorio", "vigente"],
    },
    "law_crime": {
        "label": "law, crime and justice",
        NOUN: ["juicio", "abogado", "multa", "robo", "testigo", "ladrón", "denuncia"],
        VERB: ["denunciar", "robar", "detener", "juzgar", "castigar", "huir"],
        ADJECTIVE: ["culpable", "inocente", "ilegal"],
    },
    "education": {
        "label": "school, university and studying",
        NOUN: ["asignatura", "nota", "apuntes", "beca", "aula", "pizarra", "matrícula"],
        VERB: [
            "aprobar",
            "suspender",
            "repasar",
            "matricularse",
            "copiar",
            "memorizar",
        ],
        ADJECTIVE: ["aplicado", "exigente", "optativo"],
    },
    "trades_professions": {
        "label": "trades and professions",
        NOUN: [
            "fontanero",
            "albañil",
            "enfermero",
            "panadero",
            "peluquero",
            "taller",
            "carpintero",
        ],
        VERB: ["contratar", "despedir", "ascender", "jubilarse", "atender"],
        ADJECTIVE: ["autónomo", "cualificado", "temporal"],
    },
    "sports_games": {
        "label": "sports and games",
        NOUN: [
            "balón",
            "portería",
            "árbitro",
            "carrera",
            "empate",
            "marcador",
            "raqueta",
        ],
        VERB: ["marcar", "empatar", "entrenar", "lanzar", "saltar", "vencer"],
        ADJECTIVE: ["invicto", "reñido", "agotador"],
    },
    "arts_culture": {
        "label": "arts, theatre and culture",
        NOUN: [
            "cuadro",
            "escultura",
            "escenario",
            "novela",
            "estreno",
            "taquilla",
            "exposición",
        ],
        VERB: ["dibujar", "ensayar", "aplaudir", "interpretar", "estrenar"],
        ADJECTIVE: ["conmovedor", "aburrido", "polémico"],
    },
    "devices": {
        "label": "everyday devices and gadgets",
        NOUN: [
            "pantalla",
            "teclado",
            "cargador",
            "batería",
            "contraseña",
            "auriculares",
            "mando",
        ],
        VERB: ["descargar", "borrar", "cargar", "apagar", "encender", "bloquearse"],
        ADJECTIVE: ["inalámbrico", "lento", "descargado"],
    },
    "family_relationships": {
        "label": "family, relationships and life events",
        NOUN: ["suegro", "cuñado", "nieto", "pareja", "boda", "bautizo", "sobrino"],
        VERB: [
            "casarse",
            "divorciarse",
            "abrazar",
            "pelearse",
            "reconciliarse",
            "nacer",
        ],
        ADJECTIVE: ["soltero", "viudo", "cariñoso"],
    },
    "time_frequency": {
        "label": "time and frequency expressions",
        NOUN: ["madrugada", "siglo", "quincena", "temporada", "víspera"],
        VERB: ["soler", "tardar", "durar", "retrasar", "adelantarse"],
        ADVERB: [
            "anteayer",
            "pasado mañana",
            "a menudo",
            "enseguida",
            "de vez en cuando",
            "apenas",
            "a la larga",
        ],
    },
    "senses_descriptions": {
        "label": "the senses and physical descriptions",
        NOUN: ["olor", "ruido", "tacto", "brillo", "sombra"],
        VERB: ["oler", "tocar", "oír", "brillar", "notar"],
        ADJECTIVE: ["áspero", "suave", "pegajoso", "amargo", "ruidoso", "oscuro"],
    },
    "news_media": {
        "label": "news, media and public life",
        NOUN: [
            "titular",
            "noticia",
            "anuncio",
            "encuesta",
            "rumor",
            "periodista",
            "elecciones",
        ],
        VERB: ["anunciar", "publicar", "avisar", "quejarse", "votar", "desmentir"],
        ADJECTIVE: ["polémico", "falso", "urgente"],
    },
    "environment": {
        "label": "nature and the environment",
        NOUN: ["reciclaje", "contaminación", "sequía", "incendio", "bosque", "residuo"],
        VERB: [
            "reciclar",
            "contaminar",
            "plantar",
            "malgastar",
            "proteger",
            "extinguirse",
        ],
        ADJECTIVE: ["sostenible", "renovable", "contaminado"],
    },
    "physical_actions": {
        "label": "physical actions and movement",
        NOUN: ["empujón", "caída", "golpe", "salto"],
        VERB: [
            "caber",
            "tropezar",
            "sacudir",
            "apretar",
            "esconder",
            "empujar",
            "agarrar",
            "soltar",
            "arrastrar",
            "doblar",
        ],
        ADJECTIVE: ["torpe", "ágil"],
    },
}

# Crutch words the model drifts back to; always on the avoid list.
SPANISH_ALWAYS_AVOID = [
    "trabajo",
    "problema",
    "proyecto",
    "reunión",
    "equipo",
    "cosa",
    "necesitar",
    "trabajar",
    "hablar",
]
