# Generated by Django 5.2.8 on 2025-11-16 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Config",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=50, unique=True)),
                ("value", models.CharField(max_length=200)),
            ],
        ),
    ]
