# Generated by Django 5.2.14 on 2026-10-10 16:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("worksheet", "0004_worksheet_themes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="worksheet",
            name="language",
            field=models.CharField(
                choices=[("es", "Spanish"), ("ca", "Catalan")],
                default="es",
                max_length=2,
            ),
        ),
        migrations.AddIndex(
            model_name="worksheet",
            index=models.Index(
                fields=["user", "language", "-created_at"],
                name="worksheet_w_user_id_9abc67_idx",
            ),
        ),
    ]
